#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 27 21:03:13 2018

@author: shashankgupta
"""


class GenericHeap:
    def __init__(self):
        pass
    
    
    
def main():
    pass

def __name__ == "__main__":
    main()